#PlakaOkuma.py
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 843) #Ekran boyutları
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(660, 0, 420, 811)) #Tablo kordinatları ve genişkik yükseklik değerleri
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5) #Sutun sayısı
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item) #Sutunları isimlendirebilmek için herozontal item ekliyoruz.
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.ResimLabel = QtWidgets.QLabel(self.centralwidget)
        self.ResimLabel.setGeometry(QtCore.QRect(0, 10, 640, 480)) #Kamera görüntüsünün alınacağı label boyut ayarlaması
        self.ResimLabel.setStyleSheet("background-color: rgb(50,50,50)") #Arka plan ayarlaması
        self.ResimLabel.setText("")
        self.ResimLabel.setObjectName("ResimLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 500, 250, 80)) #Başlat buttonunun boyutlarının ayarlanması
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 500, 250, 80)) #Durdur buttonunun boyutlarının ayarlanması
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.AramaTable = QtWidgets.QTableWidget(self.centralwidget)
        self.AramaTable.setGeometry(QtCore.QRect(10, 590, 381, 241)) #Arama Tablosu boyutları
        self.AramaTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AramaTable.setObjectName("AramaTable")
        self.AramaTable.setColumnCount(5)
        self.AramaTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.AramaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.AramaTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.AramaTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.AramaTable.setHorizontalHeaderItem(3, item)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(400, 600, 141, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(400, 650, 141, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(400, 700, 141, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.PlakaAra = QtWidgets.QPushButton(self.centralwidget)
        self.PlakaAra.setGeometry(QtCore.QRect(560, 600, 81, 31))
        self.PlakaAra.setObjectName("PlakaAra")
        self.TarihAra = QtWidgets.QPushButton(self.centralwidget)
        self.TarihAra.setGeometry(QtCore.QRect(560, 650, 81, 31))
        self.TarihAra.setObjectName("TarihAra")
        self.YontemAra = QtWidgets.QPushButton(self.centralwidget)
        self.YontemAra.setGeometry(QtCore.QRect(560, 700, 81, 31))
        self.YontemAra.setObjectName("YontemAra")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plaka Tespit Programı"))
        self.pushButton.setText(_translate("MainWindow", "Baslat"))
        self.pushButton_2.setText(_translate("MainWindow", "Durdur"))
        self.PlakaAra.setText(_translate("MainWindow", "Plaka Ara"))
        self.TarihAra.setText(_translate("MainWindow", "Tarih Ara"))
        self.YontemAra.setText(_translate("MainWindow", "Yontem Ara"))
        item = self.tableWidget.horizontalHeaderItem(0) #Tablo sutunlarının isimlendirilmesi.
        item.setText(_translate("MainWindow", "Okunan Plaka"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Saat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yontem"))

        #Arama Tablosu sutunlarının isimlendirilmesi.
        item = self.AramaTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Okunan Plaka"))
        item = self.AramaTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.AramaTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Saat"))
        item = self.AramaTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yontem"))


